// This file was auto-generated by ML.NET Model Builder.
using System;
using Microsoft.Maui.Storage;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace FuelWise_IA
{
    public partial class MassAirFlow
    {
        /// <summary>
        /// model input class for MassAirFlow.
        /// </summary>

        #region model input class

        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"EngineLoad")]
            public float EngineLoad { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"RPM")]
            public float RPM { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"IntakeManifoldPressure")]
            public float IntakeManifoldPressure { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"MassAirFlow")]
            public float MassAirFlow { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"IntakeAirTemperature")]
            public float IntakeAirTemperature { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"ThrottlePosition")]
            public float ThrottlePosition { get; set; }
        }

        #endregion model input class

        /// <summary>
        /// model output class for MassAirFlow.
        /// </summary>

        #region model output class

        public class ModelOutput
        {
            [ColumnName(@"EngineLoad")]
            public float EngineLoad { get; set; }

            [ColumnName(@"RPM")]
            public float RPM { get; set; }

            [ColumnName(@"IntakeManifoldPressure")]
            public float IntakeManifoldPressure { get; set; }

            [ColumnName(@"MassAirFlow")]
            public float MassAirFlow { get; set; }

            [ColumnName(@"IntakeAirTemperature")]
            public float IntakeAirTemperature { get; set; }

            [ColumnName(@"ThrottlePosition")]
            public float ThrottlePosition { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }
        }

        #endregion model output class

        //private static string MLNetModelPath = Path.GetFullPath("MassAirFlow.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new(CreatePredictEngine, true);

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            using var stream = FileSystem.OpenAppPackageFileAsync("MassAirFlow.mlnet").GetAwaiter().GetResult();
            ITransformer mlModel = mlContext.Model.Load(stream, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}